### PR TITLE
Add Django 3.0 support

### LINKED ISSUE #273: django 3.0

### PR DESCRIPTION
**Pull request by OskarPersson**
Fixes #273

### CODE REVIEW

**Comment by ruslankrivoshein** [comment]
There is also an error
```
File "/home/ruslankrivoshein/Documents/ads/venv/lib/python3.7/site-packages/rest_framework_extensions/compat.py", line 7, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/ruslankrivoshein/Documents/ads/venv/lib/python3.7/site-packages/django/utils/__init__.py)
```

**Comment by OskarPersson** [comment]
@ruslankrivoshein Are you sure you're running the correct version? That line was removed in #253 and as you can see [here](https://github.com/OskarPersson/drf-extensions/blob/dj3/rest_framework_extensions/compat.py) it is not in my branch either.

**Comment by SulanthaM** [comment]
Hi the whl file in the Pypi isnt updated with the chnages. The tar.gz is, but the whl file still contain import six from django.utils

**Comment by ognjenantonijevic** [comment]
Can confirm problem is still present with python 3.8 , Django 3.0.9 and DRF 3.11.0...

  File "/usr/src/app/authentication/urls.py", line 15, in <module>
    from . import views
  File "/usr/src/app/authentication/views.py", line 3, in <module>
    from rest_framework.views import APIView
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.8/site-packages/rest_framework/schemas/__init__.py", line 34, in <module>
    permission_classes=api_settings.DEFAULT_PERMISSION_CLASSES,
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 220, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework.permissions.IsAuthenticated' for API setting 'DEFAULT_PERMISSION_CLASSES'. ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.8/site-packages/django/utils/__init__.py).

**Pull request merged**
