### PR TITLE
Respect parent lookup regex value (sending parent viewset to NestedRegistryItem)

### PR DESCRIPTION
**Pull request by frwickst**
A try for this was made in #63 but it did not lead anywhere and this is really starting to become a problem for me so hopefully this is good enough :)

### Problem
Say that you have a user route (/users) and you do not want to expose the `id` value of the user, so you use the users email instead. Making a detailed route look like /users/frwickst@gmail.com. You test the route and notice that you get a 404 page. This is because the default lookup regex is `[^/.]+`, and this works fine for most routes, but not when there is a dot (.) in the route. And since dots are [valid in a url](http://stackoverflow.com/a/7555609) we this is a shame. The solution to this is to set your `lookup_filed` to 'email' and write your own [lookup_value_regex](http://www.django-rest-framework.org/api-guide/routers/#simplerouter) in your view. In this case we could set it to something fancy such as `[^@]+@[^@]+\.[^@/]+`. And voilà, the route now works.

The problem is that this regex value is **not** respected in the nested routers that are included in drf-extensions, instead the hard coded value of [`[^/.]+`](https://github.com/chibisov/drf-extensions/blob/f3f62290bd9970da5c1fac02275b87cfbb5ab73b/rest_framework_extensions/routers.py#L178) is used.

### Solution
By default we do not have access to the parents regex value as it is stored in the parents viewset, which we don't have access to either. This pull requests lets the viewset of the parent be passed to the ´NestedRegistryItem´ class, exposing all viewset functions and variables, including the regex. The regex is then used when creating the `get_parent_prefix()`, and falls back on the default value of `[^/.]+` if no regex is set.

### Caveat
There is a second thing here to keep in mind. If using custom lookup_field values in the view, one also needs to set the `lookup_url_kwarg` value when using nested router, in the example above it would be `lookup_url_kwarg = 'parent_lookup_email'`. This has to do with the way the `NestedViewSetMixin` is built, and can probably be fixes as well (just not in this pull request).

### CODE REVIEW

**Comment by chibisov** [comment]
I'll look at this pull request as soon as possible

**Comment by clintonb** [comment]
I, too, need this functionality added to make `drf-extensions` usable fro my API.

**Comment by clintonb** [comment]
@chibisov Any update on merging this PR?

**Comment by chibisov** [comment]
I'll merge it in next two days. Sorry for the delay.

**Comment by frwickst** [comment]
Ping!

If you are no longer working on drf-extensions it might be a good idea to create a community around it and give more people write access to the repository.

**Comment by clintonb** [comment]
@chibisov is this project still alive?

**Comment by frwickst** [comment]
Wow... so you are taking my code, without taking my commits. Basically leaving out of the fix. This is not OK with me, please include my commit and add your own code as separate commits.

**Comment by chibisov** [comment]
This is first time somebody asks me to do that :) I'm just curious, for what?

**Comment by frwickst** [comment]
Really, so you have done this before? 

This is how open source software works, else there will be no record of me contributing to the code base. It is like me giving you something, and you telling everyone you made it the way you have done it now. GitHub provides a merge button for a reason.

**Comment by chibisov** [comment]
I've merged your commits. Is that ok now?

**Comment by frwickst** [comment]
Yes, thank you. But please don't do anything like this in the future, ever. The code that people give to you are written by people wanting to help. Not including them in the commit history leaves no track of their contribution and feels like a slap in the face to many. 

Think of it like me taking your repo, and then I change all the commits to be mine instead of yours, I don't think you would like that very much. It would be basically me stealing your code. That is, in a smaller scale, what you would be doing by including other peoples code but not giving them credit in any way. If you absolutely must include other peoples code without including their commits, then at least include them in the commit message or in the code as comments in some way.

**Comment by chibisov** [comment]
Never again! ✊

**Pull request closed without merging**
