### PR TITLE
added django 2.1 on test matrix

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
@PetrDlouhy could you suggest the fix for the Django 2.1 failure?

**Comment by joehybird** [comment]
After some search, I've found that `view` permissions where added by default in Django 2.1

This issue is caused by the PermissionsComment model (see `tests_app/tests/functional/permissions/extended_django_object_permissions/models.py`)

All the `extended_django_object_permissions` module seems to need a complete refactor.
Sorry, but I'm a complete novice of this project, I don't even known the purpose of this  module.

**Comment by auvipy** [comment]
thanks for pointing! will take care of them!

**Comment by joehybird** [comment]
I've done some work, so it is here if can help.
[https://github.com/chibisov/drf-extensions/compare/master...joehybird:master]

**Comment by joehybird** [comment]
Great work @kevin-brown :) I've added little changes for test compatibility with drf 3.7 here https://github.com/chibisov/drf-extensions/pull/246 (3.8 breakings are a real pain)

**Comment by johnthagen** [comment]
Somewhat duplicates #248

**Pull request closed without merging**
