### PR TITLE
Fail fast on unit tests and default params for key bits

### PR DESCRIPTION
**Pull request by expobrain**
- Stop unit tests upon first fail: there's no need to continue further in the tests
- Args, Kwargs and Query KeyBits have params set to '*' by default: having any of this key bits without '*' is meaningless

### CODE REVIEW

**Comment by chibisov** [comment]
Good point about usage of `*` by default. Please, add to documentation information about this default behaviour for `QueryParamsKeyBit`, `ArgsKeyBit` and `KwargsKeyBit`

I don't like default `--failfast` behaviour:
```
{envbindir}/django-admin.py test --settings=settings {posargs} --failfast
```

I won't be possible to start tox tests without `--failfast` option.
If you want to start it with `--failfast` just use it with tox command:

```
tox -- tests_app --failfast
```

**Comment by expobrain** [comment]
Do you need some other changes on this pull request?

**Comment by chibisov** [comment]
No, I'll merge it today. Thank you for contribution.

**Comment by expobrain** [comment]
My 2 cents

**Pull request merged**
