### PR TITLE
Fix all failing tests

### PR DESCRIPTION
**Pull request by jcugat**
I have fixed all the tests that were failing with `django.1.8.lts`. There is still work to do to fix them with `django.1.9` and `django.1.10`.

Instead of opening a pull request for every change, I've grouped all the changes in different commits to help review it.

By the way @auvipy, you should be more careful when making changes in this project. I had to revert a lot of the work that you did in #140 because most of them where wrong or didn't fix the tests at all.

### CODE REVIEW

**Comment by auvipy** [comment]
that;s awesome. i will review and merge ASAP.

**Comment by jcugat** [comment]
Any word on a PyPI release?

**Comment by chibisov** [comment]
Hi. I have keys for publishing new pypi releases. I would love to release new version but there is still no compatibility with django 1.9 and 1.10 (#164)

**Comment by auvipy** [comment]
what about a release with 1.8 support only?

**Comment by chibisov** [comment]
It's better to release with 1.9 and 1.10 support. If you don't think it isn't feasible in near future I'll release the current version of the package.

**Comment by jcugat** [comment]
Let me take a quick look at what's missing for django 1.9 and 1.10.

**Comment by jcugat** [comment]
Hi @chibisov I have fixed all the remaining tests with Django 1.9 and 1.10 in #166.

Another thing is I think the tox/travis test matrix should be updated with the versions of DRF it supports. Maybe test it against DRF 3.2/3.3/3.4 at least? What do you think?

**Comment by garykrige** [comment]
thanks @jcugat this is a great PR! was just about to start trying to get into this and now I see its all done. I guess this can be released now. :D

**Comment by auvipy** [comment]
@garykrige you could still help with change log/documentation for a pypi release.

**Pull request merged**
