### PR TITLE
Add limit/offset and cursor pagination to PaginationKeyBit

### LINKED ISSUE #203: PaginationKeyBit does not consider LimitOffsetPagination and CursorPagination
[PaginationKeyBit](https://github.com/chibisov/drf-extensions/blob/master/rest_framework_extensions/key_constructor/bits.py#L168) only uses `page_query_param` and `page_query_size_param`.

missing:
- [LimitOffsetPagination](http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination): `limit_query_param` & `offset_query_param`
- [CursorPagination](http://www.django-rest-framework.org/api-guide/pagination/#cursorpagination): `cursor_query_param`

### PR DESCRIPTION
**Pull request by fdemmer**
fixes #203

### CODE REVIEW

**Comment by hjalves** [comment]
Hi! Can you merge this PR? Is there anything missing I can do? Thanks ^^

**Comment by auvipy** [comment]
is this patch fixed your problem? you can help with functional and unit test

**Comment by hjalves** [comment]
Ok, I'll try to make some tests

**Comment by auvipy** [comment]
anyone up fr the tests? and manually verify?

**Comment by fdemmer** [comment]
I've had my fork in use for a while now without problems and finally added tests for the two other paginators.

**Comment by auvipy** [comment]
thanks a lot!

**Pull request merged**
