### PR TITLE
Made compatible with DRF 3.2.2 and django 1.8

### PR DESCRIPTION
**Pull request by pratyushmittal**
Hi Gennady,

I have made a few changes to make drf-extensions compatible with the latest Django Rest Framework. The new versions of Django Rest Framework, since 3.1.0, have introduced some breaking changes, such as the new Pagination classes. The tests pass with these recent versions only.

How about considering to drop the support for earlier versions? We can add some note like:

> For Django Rest Framework 2.4 support check drf-extensions 0.2.7

Thanks for creating and sharing the extensions.

### CODE REVIEW

**Comment by rocjojo** [comment]
Hello,

Any news about that ? I'm struggling with pagination as well...

**Comment by codingjoe** [comment]
:+1: support for the latest DRF version would be great!

**Comment by auvipy** [comment]
@pratyushmittal hi thanks for your works, would u mind restesting and rebasing against drf 3.3.1?

**Comment by auvipy** [comment]
should consider this #113

**Comment by auvipy** [comment]
@pratyushmittal would you please update the PR to pass the CI build?

**Comment by pratyushmittal** [comment]
Hi @auvipy , it is good to see the reincarnation of this awesome library.

In the pull request, I have dropped the support of old DRF versions (due to the new Pagination Class implementation). I have also included new tests for this. Travis CI is still building against the old tests. Any workaround to see the Travis results for the new tests included?

**Comment by auvipy** [comment]
thanks for your effort. will check CI n your code. I'm also planning to drop support of older versions of DRF and django itself too

**Comment by codingjoe** [comment]
:+1: and old python versions ;)
http://cdn.meme.am/instances/63860744.jpg

**Comment by auvipy** [comment]
@codingjoe python 2.7, 3.4 and 3.5 will be supported as django supports them.

**Comment by pratyushmittal** [comment]
I have updated the Tox file to test against the latest, LTS and supported python versions.

**Comment by auvipy** [comment]
you need to update travis.yml too :) and keep support of 1.7 for now :)

**Comment by pratyushmittal** [comment]
All the tests are passing except for Django 1.7 on Python 3.5. Django 1.7 did not support 3.5.

**Comment by codingjoe** [comment]
This should do it
travis.yml
```
matrix:
  allow_failures:
    - env: DJANGO="Django<1.8,>=1.7"
      python: "3.5"
```

**Comment by pratyushmittal** [comment]
@codingjoe Thanks. Have excluded Django1.7 for Python 3.5 tests.

I have also changed the hash algorithm used for caching of key constructor from sha256 to md5.
SHA256 is inherently meant to be slow as it is meant for security use-cases.
For caching we need a faster hash generation only for unique keys.
NGINX uses md5 for cache keys.

**Comment by auvipy** [comment]
thanks @pratyushmittal for your works! @codingjoe for your insights!! ;)

**Pull request merged**
