### PR TITLE
Fixed PaginationKeyBit

### PR DESCRIPTION
**Pull request by tevinjoseph**
PaginationKeyBit wasn't working the way it was meant to. It gave same results for all pages.

### CODE REVIEW

**Comment by auvipy** [comment]
test?

**Comment by tevinjoseph** [comment]
@auvipy PaginationKeyBit is an existing piece of code. So, I believe there are tests written for it. No tests are breaking then, it is working fine, I guess.

**Comment by auvipy** [comment]
kool

**Comment by chibisov** [comment]
Come on, guys. First of all tests `tests_app.tests.unit.key_constructor.bits.tests.PaginationKeyBitTest` are failing.

Second - you've hardcoded `page_query_param` name as `page`. If someone uses another name it will fail.

Please, revert it and be more careful. Thank you for contribution.

**Comment by auvipy** [comment]
@tevinjoseph reverted

**Pull request merged**
