### PR TITLE
Revert "Fixed PaginationKeyBit"

### PR DESCRIPTION
**Pull request by auvipy**
Reverts chibisov/drf-extensions#146

### CODE REVIEW

**Comment by randvis** [comment]
@auvipy Thanks for your efforts on maintaining drf-extensions. 👍 

May I know when this revert will be released to PyPI?

**Comment by auvipy** [comment]
@randvis I'm sorry for not able to push a pypi release yet. but I have and interest to have a pypi release before the end of this month.

**Comment by randvis** [comment]
That's great! Thanks a lot.

**Comment by fdemmer** [comment]
related: #203

**Pull request merged**
