### PR TITLE
Added MappingField

### PR DESCRIPTION
**Pull request by Anton-Shutik**

### CODE REVIEW

**Comment by auvipy** [comment]
osetests tests_app --processes=32 --process-timeout=100 --nocapture --verbosity=1
/home/travis/build/chibisov/drf-extensions/tests_app/tests/functional/permissions/extended_django_object_permissions/tests.py:5: RemovedInDjango19Warning: django.utils.unittest will be removed in Django 1.9.
  from django.utils import unittest
/home/travis/build/chibisov/drf-extensions/tests_app/tests/functional/routers/nested_router_mixin/models.py:3: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic
Creating test database for alias 'default'...
E..............SSSS..............................................................................................................................................S...........................S..S......................
======================================================================
ERROR: Failure: ImportError (No module named 'rest_framework.tests')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/chibisov/drf-extensions/.tox/django.1.8.lts/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/build/chibisov/drf-extensions/.tox/django.1.8.lts/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/chibisov/drf-extensions/.tox/django.1.8.lts/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)

**Comment by Anton-Shutik** [comment]
Yep, I saw this. Any idea why it doesn't see rest_framework.tests module ?

**Comment by chibisov** [comment]
Please, add docs to `index.md` file and then generate `index.html`. As I understood, you've change html file directly.

**Comment by auvipy** [comment]
rebuild localy and resend again kindly

**Pull request closed without merging**
