### PR TITLE
Add paginate decorator

### PR DESCRIPTION
**Pull request by no-dap**
Decorator to add paginate class. Send PR requested by @auvipy 
[https://github.com/encode/django-rest-framework/pull/6945](https://github.com/encode/django-rest-framework/pull/6945)

### CODE REVIEW

**Comment by no-dap** [comment]
I can't find the location to place my tests. Can anyone tell me where should I put it on?

**Comment by auvipy** [comment]
https://github.com/chibisov/drf-extensions/tree/master/tests_app/tests

**Comment by no-dap** [comment]
thanks XD

**Comment by no-dap** [comment]
By the way, thank you for introducing me this lovely project. This looks really useful.

**Comment by auvipy** [comment]
more addons will be added on this project in near future :)

**Comment by no-dap** [comment]
I'm a little worried about English is not my first language.

**Pull request merged**
